version: '3.11'

services:
  toonhavencentral:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
        - POSTGRES_HOST=localhost
        - POSTGRES_USER=rownokn
        - POSTGRES_PASSWORD=InuyashaBleach$1
        - POSTGRES_DB=toonhavencentral
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:17.0-bookworm
    ports:
      - 5434:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # Mount the SQL script folder
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=toonhavencentral
      - POSTGRES_USER=rownokn
      - POSTGRES_PASSWORD=InuyashaBleach$1
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: