# Generated by Django 5.1.1 on 2024-11-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("game_id", models.IntegerField()),
                ("goal_description", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "custom_goal",
            },
        ),
        migrations.CreateModel(
            name="GamingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("game_id", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.DurationField(blank=True, null=True)),
                ("level", models.CharField(blank=True, max_length=100, null=True)),
                ("notable_events", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gaming_session",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("user_id", models.IntegerField()),
                ("profile_name", models.CharField(max_length=255, unique=True)),
                ("profile_picture", models.CharField(max_length=255)),
                ("bio", models.TextField(null=True)),
                ("login_token", models.CharField(max_length=50)),
                ("oauth_provider", models.CharField(max_length=50, null=True)),
                ("oauth_id", models.CharField(max_length=128, null=True, unique=True)),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="SessionReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("strategies", models.TextField(blank=True, null=True)),
                ("emotional_response", models.TextField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection",
                        to="app.gamingsession",
                    ),
                ),
            ],
            options={
                "db_table": "session_reflection",
            },
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("game_id", models.SmallIntegerField()),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Not Playing"),
                            (2, "Currently Playing"),
                            (3, "Finished"),
                            (-1, "Stop Playing"),
                        ]
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_users",
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_game",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("description", models.CharField(max_length=255)),
                ("remind_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customgoal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "reminder",
            },
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("game_id", models.IntegerField()),
                ("mood_before", models.CharField(max_length=50)),
                ("mood_after", models.CharField(max_length=50)),
                ("custom_mood", models.CharField(blank=True, max_length=50, null=True)),
                ("date_logged", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.gamingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moods",
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mood",
            },
        ),
        migrations.CreateModel(
            name="InsightReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("generated_on", models.DateField(auto_now_add=True)),
                ("most_played_game_id", models.IntegerField()),
                ("average_session_length", models.DurationField()),
                ("total_playtime", models.DurationField()),
                ("mood_trend_analysis", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_reports",
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "insight_report",
            },
        ),
        migrations.AddField(
            model_name="gamingsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gaming_sessions",
                to="app.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("CSV", "CSV")], max_length=10
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "data_export",
            },
        ),
        migrations.AddField(
            model_name="customgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_goals",
                to="app.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField(max_length=50)),
                (
                    "sessions",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="app.gamingsession"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_tag",
            },
        ),
    ]
