# Generated by Django 5.1.1 on 2024-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=255)),
                ("alternative_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[
                            (0, "----"),
                            (1, "Console"),
                            (2, "Arcade"),
                            (3, "Platform"),
                            (4, "Operating System"),
                            (5, "Portable Console"),
                            (6, "Computer"),
                        ],
                        default=0,
                    ),
                ),
                ("generation", models.IntegerField()),
                ("slug", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("url", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "platform",
            },
        ),
    ]
