# Generated by Django 5.1.1 on 2024-11-03 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_cover_franchise_genre_platform_platformlogo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("trusted", models.BooleanField()),
                ("url", models.CharField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (1, "Official"),
                            (2, "Wikia"),
                            (3, "Wikipedia"),
                            (4, "Facebook"),
                            (5, "Twitter"),
                            (6, "Twitch"),
                            (8, "Instagram"),
                            (9, "Youtube"),
                            (10, "IPhone"),
                            (11, "IPad"),
                            (12, "Android"),
                            (13, "Steam"),
                            (14, "Reddit"),
                            (15, "Itch"),
                            (16, "Epic Games"),
                            (17, "GOG"),
                            (18, "Discord"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_web",
                        to="app.game",
                    ),
                ),
            ],
            options={
                "db_table": "game_website",
            },
        ),
    ]
