# Generated by Django 5.1.1 on 2024-10-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "genre",
            },
        ),
    ]
