# Generated by Django 5.1.1 on 2024-10-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("height", models.IntegerField()),
                ("image_id", models.CharField()),
                ("url", models.CharField()),
                ("width", models.IntegerField()),
                ("alpha_channel", models.BooleanField()),
                ("animated", models.BooleanField()),
            ],
            options={
                "db_table": "platform_logo",
            },
        ),
    ]
