# Generated by Django 5.1.1 on 2024-10-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_platformlogo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("profile_name", models.CharField(unique=True)),
                ("profile_picture", models.CharField()),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("bio", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("login_token", models.CharField(max_length=50)),
                ("oauth_provider", models.CharField(max_length=50, null=True)),
                ("oauth_id", models.CharField(max_length=128, null=True, unique=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
