# Generated by Django 5.1.1 on 2024-10-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profile",
        ),
    ]
