# Generated by Django 5.1.1 on 2024-11-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_achievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField()),
            ],
            options={
                "db_table": "platform_family",
            },
        ),
        migrations.CreateModel(
            name="ReleaseDateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "release_date_status",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "theme",
            },
        ),
        migrations.RenameField(
            model_name="game",
            old_name="platform",
            new_name="platforms",
        ),
        migrations.AddField(
            model_name="game",
            name="alternative_names",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="expanded_games",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="websites",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cover",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covers",
                to="app.game",
            ),
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("height", models.IntegerField()),
                ("image_id", models.CharField()),
                ("url", models.CharField()),
                ("width", models.IntegerField()),
                ("alpha_channel", models.BooleanField()),
                ("animated", models.BooleanField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="app.game",
                    ),
                ),
            ],
            options={
                "db_table": "artwork",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                ("name", models.CharField()),
                ("slug", models.CharField()),
                ("url", models.CharField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="app.game",
                    ),
                ),
            ],
            options={
                "db_table": "keyword",
            },
        ),
        migrations.CreateModel(
            name="ReleaseDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.UUIDField()),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[
                            (0, "YYYYMMMMDD"),
                            (1, "YYYYMMMM"),
                            (2, "YYYY"),
                            (3, "YYYYQ1"),
                            (4, "YYYYQ2"),
                            (5, "YYYYQ3"),
                            (6, "YYYYQ4"),
                            (7, "TBD"),
                        ]
                    ),
                ),
                ("date", models.DateTimeField()),
                ("human", models.CharField(max_length=255)),
                ("m", models.SmallIntegerField()),
                (
                    "region",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Europe"),
                            (2, "North America"),
                            (3, "Austrailia"),
                            (4, "New Zealand"),
                            (5, "Japan"),
                            (6, "China"),
                            (7, "Asia"),
                            (8, "WorldWide"),
                            (9, "Korea"),
                            (10, "Brazil"),
                        ]
                    ),
                ),
                ("y", models.SmallIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_dates",
                        to="app.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="app.platform",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_date_status",
                        to="app.game",
                    ),
                ),
            ],
            options={
                "db_table": "release_date",
            },
        ),
    ]
