# Generated by Django 5.1.1 on 2024-11-12 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_platformfamily_releasedatestatus_theme_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="cover",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gamingsession",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="mood",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="usergame",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_id",
        ),
        migrations.AddField(
            model_name="achievement",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="gamingsession",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_gaming_sessions",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="mood",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moods",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="usergame",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_games",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamingsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_gaming_sessions",
                to="app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="sessionreflection",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_reflections",
                to="app.gamingsession",
            ),
        ),
        migrations.AlterField(
            model_name="usergame",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_games",
                to="app.userprofile",
            ),
        ),
    ]
