# Generated by Django 5.1.1 on 2024-11-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_achievement_game_id_remove_cover_game_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customgoal",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="insightreport",
            name="most_played_game_id",
        ),
        migrations.AddField(
            model_name="customgoal",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_goals",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="insightreport",
            name="most_played_game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insight_reports",
                to="app.game",
            ),
        ),
    ]
