# Generated by Django 5.1.1 on 2024-11-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_customgoal_game_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="game",
            name="screenshots",
        ),
        migrations.RemoveField(
            model_name="game",
            name="websites",
        ),
    ]
