# Generated by Django 5.1.1 on 2024-11-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_game_aggregated_rating_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="aggregated_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="game",
            name="total_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
