# Generated by Django 5.1.1 on 2024-11-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_game_aggregated_rating_alter_game_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cover",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover",
                to="app.cover",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_perspectives",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_perspectives",
                to="app.playerperspectives",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="version_parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_game",
                to="app.game",
            ),
        ),
    ]
