# Generated by Django 5.1.1 on 2024-11-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_game_cover_alter_game_player_perspectives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="franchise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="franchises",
                to="app.franchise",
            ),
        ),
    ]
